#!/bin/sh -eux
qemu-kvm -m 4G \
	-bios $(nix-build --no-out-link -A OVMF.fd '<nixpkgs>')/FV/OVMF.fd \
	-cpu host \
	-display gtk,gl=on \
	-device virtio-vga-gl \
	-device qemu-xhci \
	-device usb-storage,drive=drive1,removable=true \
	-drive file=$(nix-build --no-out-link live.nix),id=drive1,format=raw,if=none,readonly=true
