#!/usr/bin/awk -f
# SPDX-License-Identifier: EUPL-1.2+
# SPDX-FileCopyrightText: 2021 Alyssa Ross <hi@alyssa.is>

function driver(type) {
	sub("\\.ko$", "")
	print $NF, "\"/etc/mdev/" type "/$ACTION\""
}

BEGIN {
	FS = "/"
	OFS = "\t"

	# Break this up to avoid confusing reuse lint.
	print "# SPDX-License-Identifier" ": CC0-1.0"
	print "#"
	print "# Generated by gen_modules.map.awk."
}

FNR == 1 {
	print ""
	print "# Input file: " FILENAME
}

/^kernel\/drivers\/net\/ethernet\// { driver("net") }
