#!/bin/awk -f
# SPDX-License-Identifier: EUPL-1.2
# SPDX-FileCopyrightText: 2020-2021 Alyssa Ross <hi@alyssa.is>
#
# Calculate the MACs for our TAP and the router's TAP, based on the
# pid of the main VMM process to ensure uniqueness.  MAC address
# format, by octet:
#
#  0-3  Static OUI for Spectrum
#    4  Most significant bit is used to differentiate routers from
#       clients.  Other bits are reserved.
#  5-6  Last two octets of client's IP (in 100.64.0.0/16).
#
# Parameters:
# 	-v pid=PID	pid of the main VMM process
# 	-v octet4=VAL	hex value to be used as octet 4 in the address

BEGIN {
  hex = sprintf("%.4x", pid);
  print "0A:B3:EC:" octet4 ":" substr(hex, 0, 2) ":" substr(hex, 3);
}
